import { useState } from 'react'
import { generateDiet } from '../services/api'
import ReactMarkdown from 'react-markdown'
import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'
import { FaRobot, FaDownload, FaSpinner } from 'react-icons/fa'

const GenerateDiet = () => {
  const [dietChart, setDietChart] = useState('')
  const [loading, setLoading] = useState(false)
  const [downloading, setDownloading] = useState(false)
  const [error, setError] = useState('')
  const [bmi, setBmi] = useState(null)
  const [bmiCategory, setBmiCategory] = useState('')

  const handleGenerate = async () => {
    setLoading(true)
    setError('')
    try {
      const { data } = await generateDiet()
      setDietChart(data.dietChart)
      setBmi(data.bmi)
      setBmiCategory(data.bmiCategory)
    } catch (err) {
      setError(err.response?.data?.message || 'Failed to generate diet chart')
    } finally {
      setLoading(false)
    }
  }

const handleDownloadPDF = () => {
  setDownloading(true)
  try {
    const pdf = new jsPDF('p', 'mm', 'a4')
    const pageWidth = pdf.internal.pageSize.getWidth()
    const pageHeight = pdf.internal.pageSize.getHeight()
    const margin = 15
    const maxWidth = pageWidth - margin * 2
    let y = 20

    // Header
    pdf.setFillColor(21, 128, 61)
    pdf.rect(0, 0, pageWidth, 30, 'F')
    pdf.setTextColor(255, 255, 255)
    pdf.setFontSize(20)
    pdf.setFont('helvetica', 'bold')
    pdf.text('Your Personalized Diet Chart', pageWidth / 2, 18, { align: 'center' })
    pdf.setFontSize(10)
    pdf.text('Generated by DietAI — Powered by AI', pageWidth / 2, 26, { align: 'center' })

    y = 45

    // BMI Info
    pdf.setTextColor(0, 0, 0)
    pdf.setFontSize(12)
    pdf.setFont('helvetica', 'bold')
    pdf.text(`BMI: ${bmi} (${bmiCategory})`, margin, y)
    y += 10

    // Clean the diet chart text
    const cleanText = dietChart
      .replace(/#{1,6}\s/g, '')
      .replace(/\*\*/g, '')
      .replace(/\*/g, '')
      .replace(/`/g, '')

    const lines = cleanText.split('\n').filter(line => line.trim() !== '')

    pdf.setFont('helvetica', 'normal')
    pdf.setFontSize(10)

    lines.forEach((line) => {
      const trimmed = line.trim()
      if (!trimmed) return

      // Check if new page needed
      if (y > pageHeight - 20) {
        pdf.addPage()
        y = 20
      }

      // Style headings differently
      if (trimmed.endsWith(':') || trimmed.match(/^\d+\./)) {
        pdf.setFont('helvetica', 'bold')
        pdf.setTextColor(21, 128, 61)
        pdf.setFontSize(11)
      } else {
        pdf.setFont('helvetica', 'normal')
        pdf.setTextColor(50, 50, 50)
        pdf.setFontSize(10)
      }

      const splitLines = pdf.splitTextToSize(trimmed, maxWidth)
      pdf.text(splitLines, margin, y)
      y += splitLines.length * 6
    })

    pdf.save('my-diet-chart.pdf')
  } catch (err) {
    console.log('PDF Error:', err)
    alert('Error: ' + err.message)
  } finally {
    setDownloading(false)
  }
}

  return (
    <div className='min-h-screen bg-gradient-to-br from-green-50 to-emerald-100 p-8'>
      <div className='max-w-4xl mx-auto'>
        {/* Header */}
        <div className='mb-8'>
          <h2 className='text-4xl font-extrabold text-gray-800 mb-2'>Generate Diet Chart 🤖</h2>
          <p className='text-gray-500 text-lg'>Get your personalized meal plan instantly</p>
        </div>

        {error && (
          <div className='bg-red-100 text-red-600 px-4 py-3 rounded-lg mb-6'>{error}</div>
        )}

        {/* Generate Button */}
        {!dietChart && (
          <div className='bg-white rounded-3xl p-12 shadow-lg text-center'>
            <FaRobot className='text-6xl text-green-500 mx-auto mb-6' />
            <h3 className='text-2xl font-bold text-gray-800 mb-3'>Ready to generate your diet chart?</h3>
            <p className='text-gray-500 mb-8'>Our AI will analyze your profile and create a personalized meal plan just for you!</p>
            <button
              onClick={handleGenerate}
              disabled={loading}
              className='bg-green-600 text-white px-12 py-4 rounded-full text-lg font-semibold hover:bg-green-700 transition disabled:opacity-50 shadow-lg hover:shadow-xl hover:-translate-y-1 transform duration-200'
            >
              {loading ? (
                <span className='flex items-center gap-3'>
                  <FaSpinner className='animate-spin' />
                  Generating your diet chart...
                </span>
              ) : '✨ Generate My Diet Chart'}
            </button>
          </div>
        )}

        {/* Diet Chart Result */}
        {dietChart && (
          <div>
            {/* BMI + Download Bar */}
            <div className='flex justify-between items-center bg-white rounded-2xl px-6 py-4 shadow-md mb-6'>
              <div className='flex gap-6'>
                <div>
                  <span className='text-gray-400 text-sm'>Your BMI</span>
                  <div className='font-bold text-green-600 text-xl'>{bmi}</div>
                </div>
                <div>
                  <span className='text-gray-400 text-sm'>Category</span>
                  <div className='font-bold text-gray-800'>{bmiCategory}</div>
                </div>
              </div>
              <div className='flex gap-3'>
                <button
                  onClick={handleGenerate}
                  disabled={loading}
                  className='bg-gray-100 text-gray-700 px-5 py-2 rounded-full font-semibold hover:bg-gray-200 transition disabled:opacity-50'
                >
                  {loading ? 'Regenerating...' : '🔄 Regenerate'}
                </button>
                <button
                  onClick={handleDownloadPDF}
                  disabled={downloading}
                  className='bg-green-600 text-white px-5 py-2 rounded-full font-semibold hover:bg-green-700 transition disabled:opacity-50 flex items-center gap-2'
                >
                  <FaDownload />
                  {downloading ? 'Downloading...' : 'Download PDF'}
                </button>
              </div>
            </div>

            {/* Diet Chart Content */}
            <div id='diet-chart-content' className='bg-white rounded-3xl shadow-xl p-10 prose max-w-none'>
              <div className='text-center mb-8 border-b pb-6'>
                <h1 className='text-3xl font-extrabold text-green-700 mb-1'>🥗 Your Personalized Diet Chart</h1>
                <p className='text-gray-400'>Generated by BellyBoss</p>
              </div>
              <ReactMarkdown>{dietChart}</ReactMarkdown>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}

export default GenerateDiet