import { Link } from 'react-router-dom'
import { FaRobot, FaChartBar, FaHistory, FaLeaf, FaShieldAlt, FaBolt } from 'react-icons/fa'

const Home = () => {
  return (
    <div className='min-h-screen bg-gradient-to-br from-green-50 to-emerald-100'>

      {/* Hero Section */}
      <div className='flex flex-col items-center justify-center text-center px-6 py-28'>
        <div className='bg-green-100 text-green-700 px-4 py-2 rounded-full text-sm font-semibold mb-6 inline-block'>
           Eat Smarter, Live Better
        </div>
        <h1 className='text-6xl font-extrabold text-green-700 mb-6 leading-tight'>
          Your Personal <br />
          <span className='text-emerald-500'>Diet Planner</span>
        </h1>
        <p className='text-xl text-gray-600 max-w-2xl mb-10 leading-relaxed'>
          Get a fully personalized diet chart generated by us on your body type,
          health goals, and food preferences. 100% tailored just for you!<br></br>by Samadrito and his team
        </p>
        <div className='flex gap-4 flex-wrap justify-center'>
          <Link
            to='/register'
            className='bg-green-600 text-white px-10 py-4 rounded-full text-lg font-semibold hover:bg-green-700 transition shadow-xl hover:shadow-2xl hover:-translate-y-1 transform duration-200'
          >
            Get Started Free 
          </Link>
          <Link
            to='/login'
            className='border-2 border-green-600 text-green-600 px-10 py-4 rounded-full text-lg font-semibold hover:bg-green-50 transition'
          >
            Login
          </Link>
        </div>

        {/* Stats */}
        <div className='flex gap-12 mt-16 flex-wrap justify-center'>
          <div className='text-center'>
            <div className='text-3xl font-bold text-green-700'>AI</div>
            <div className='text-gray-500 text-sm'>Powered</div>
          </div>
          <div className='text-center'>
            <div className='text-3xl font-bold text-green-700'>100%</div>
            <div className='text-gray-500 text-sm'>Personalized</div>
          </div>
           <div className='text-center'>
            <div className='text-3xl font-bold text-green-700'>100+</div>
            <div className='text-gray-500 text-sm'>Members</div>
          </div>
          <div className='text-center'>
            <div className='text-3xl font-bold text-green-700'>Free</div>
            <div className='text-gray-500 text-sm'>To Use</div>
          </div>
        </div>
      </div>

      {/* Features Section */}
      <div className='px-12 pb-16'>
        <h2 className='text-3xl font-bold text-center text-gray-800 mb-12'>Everything you need </h2>
        <div className='grid grid-cols-1 md:grid-cols-3 gap-8 max-w-6xl mx-auto'>
          {[
            { icon: <FaRobot className='text-green-600 text-3xl' />, title: 'AI Powered', desc: 'Advanced AI analyzes your health data and creates a fully personalized diet plan' },
            { icon: <FaChartBar className='text-green-600 text-3xl' />, title: 'BMI Calculator', desc: 'Track your BMI and get detailed insights about your current health status' },
            { icon: <FaHistory className='text-green-600 text-3xl' />, title: 'Diet History', desc: 'Save and revisit all your past diet charts anytime in one place' },
            { icon: <FaLeaf className='text-green-600 text-3xl' />, title: 'Indian Food', desc: 'Diet plans based on Indian food culture with local ingredients' },
            { icon: <FaShieldAlt className='text-green-600 text-3xl' />, title: 'Secure', desc: 'Your health data is protected with JWT authentication and encryption' },
            { icon: <FaBolt className='text-green-600 text-3xl' />, title: 'Creator Panel', desc: 'Samadrito Khamaru, Hena Nandy, Tanisha Sinha, Krishna Murari' },
          ].map((feature, i) => (
            <div key={i} className='bg-white rounded-2xl p-8 shadow-md hover:shadow-xl transition duration-300 hover:-translate-y-1 transform'>
              <div className='mb-4'>{feature.icon}</div>
              <h3 className='text-xl font-bold text-gray-800 mb-2'>{feature.title}</h3>
              <p className='text-gray-500'>{feature.desc}</p>
            </div>
          ))}
        </div>
      </div>

      {/* CTA Section */}
      <div className='bg-green-600 text-white text-center py-20 px-6'>
        <h2 className='text-4xl font-bold mb-4'>Ready to start your health journey?</h2>
        <p className='text-green-100 text-xl mb-8'>Join thousands of people eating healthier with AI</p>
        <Link
          to='/register'
          className='bg-white text-green-600 px-10 py-4 rounded-full text-lg font-semibold hover:bg-green-50 transition shadow-xl'
        >
          Get Started Free 
        </Link>
      </div>

      {/* Footer */}
      <div className='text-center py-6 text-gray-400 text-sm'>
        Built with ❤️ using React, Node.js, MongoDB & Express
      </div>
    </div>
  )
}

export default Home