import { Link } from 'react-router-dom'

const Home = () => {
  return (
    <div className='min-h-screen bg-gradient-to-br from-green-50 to-emerald-100'>
      {/* Hero Section */}
      <div className='flex flex-col items-center justify-center text-center px-6 py-24'>
        <h1 className='text-5xl font-bold text-green-700 mb-6'>
          Your Personal Diet Planner 🥗
        </h1>
        <p className='text-xl text-gray-600 max-w-2xl mb-10'>
          Get a personalized diet chart generated by us on your body type,
          goals, and food preferences. Completely tailored just for you!<br></br>
          by-Samadrito and his team!
        </p>
        <div className='flex gap-4'>
          <Link
            to='/register'
            className='bg-green-600 text-white px-8 py-3 rounded-full text-lg font-semibold hover:bg-green-700 transition shadow-lg'
          >
            Get Started Free
          </Link>
          <Link
            to='/login'
            className='border-2 border-green-600 text-green-600 px-8 py-3 rounded-full text-lg font-semibold hover:bg-green-50 transition'
          >
            Login
          </Link>
        </div>
      </div>

      {/* Features Section */}
      <div className='grid grid-cols-1 md:grid-cols-3 gap-8 px-12 pb-24'>
        <div className='bg-white rounded-2xl p-8 shadow-md text-center'>
          <div className='text-5xl mb-4'>🤖</div>
          <h3 className='text-xl font-bold text-gray-800 mb-2'>AI Powered</h3>
          <p className='text-gray-500'>Get diet charts generated by advanced AI tailored to your needs</p>
        </div>
        <div className='bg-white rounded-2xl p-8 shadow-md text-center'>
          <div className='text-5xl mb-4'>📊</div>
          <h3 className='text-xl font-bold text-gray-800 mb-2'>BMI Calculator</h3>
          <p className='text-gray-500'>Track your BMI and get insights about your health status</p>
        </div>
        <div className='bg-white rounded-2xl p-8 shadow-md text-center'>
          <div className='text-5xl mb-4'>📋</div>
          <h3 className='text-xl font-bold text-gray-800 mb-2'>Diet History</h3>
          <p className='text-gray-500'>Save and track all your past diet charts in one place</p>
        </div>
      </div>
    </div>
  )
}

export default Home